//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipSis.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> ByPrice { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<int> WendDateID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual WendDate WendDate { get; set; }
    }
}
